'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\AukDatabase2.mdb;Per"& _ 
            "sist Security Info=True;Jet OLEDB:Database Password=lorenzom268")>  _
        Public ReadOnly Property AukDatabase2ConnectionString() As String
            Get
                Return CType(Me("AukDatabase2ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property perMoneyRate() As String
            Get
                Return CType(Me("perMoneyRate"),String)
            End Get
            Set
                Me("perMoneyRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property chktONEXT() As Boolean
            Get
                Return CType(Me("chktONEXT"),Boolean)
            End Get
            Set
                Me("chktONEXT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property Dvd_Bro_price() As String
            Get
                Return CType(Me("Dvd_Bro_price"),String)
            End Get
            Set
                Me("Dvd_Bro_price") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property CD_bro_price() As String
            Get
                Return CType(Me("CD_bro_price"),String)
            End Get
            Set
                Me("CD_bro_price") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DataLoad_view() As Boolean
            Get
                Return CType(Me("DataLoad_view"),Boolean)
            End Get
            Set
                Me("DataLoad_view") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
        Public Property MaximumData_load() As String
            Get
                Return CType(Me("MaximumData_load"),String)
            End Get
            Set
                Me("MaximumData_load") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property Maximum_Alternative() As String
            Get
                Return CType(Me("Maximum_Alternative"),String)
            End Get
            Set
                Me("Maximum_Alternative") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property Rent_Days() As String
            Get
                Return CType(Me("Rent_Days"),String)
            End Get
            Set
                Me("Rent_Days") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Fine() As String
            Get
                Return CType(Me("Fine"),String)
            End Get
            Set
                Me("Fine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Dont_RefreshData() As Boolean
            Get
                Return CType(Me("Dont_RefreshData"),Boolean)
            End Get
            Set
                Me("Dont_RefreshData") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property MaxDVD_RentNumber() As String
            Get
                Return CType(Me("MaxDVD_RentNumber"),String)
            End Get
            Set
                Me("MaxDVD_RentNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property DVDRentNumberNonReg() As String
            Get
                Return CType(Me("DVDRentNumberNonReg"),String)
            End Get
            Set
                Me("DVDRentNumberNonReg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property Cyber_per_hourRate() As String
            Get
                Return CType(Me("Cyber_per_hourRate"),String)
            End Get
            Set
                Me("Cyber_per_hourRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property CyberMinCost() As String
            Get
                Return CType(Me("CyberMinCost"),String)
            End Get
            Set
                Me("CyberMinCost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("InStore")>  _
        Public Property Place_NormalSearch() As String
            Get
                Return CType(Me("Place_NormalSearch"),String)
            End Get
            Set
                Me("Place_NormalSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ProductName_Search() As String
            Get
                Return CType(Me("ProductName_Search"),String)
            End Get
            Set
                Me("ProductName_Search") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property place_chk_src() As Boolean
            Get
                Return CType(Me("place_chk_src"),Boolean)
            End Get
            Set
                Me("place_chk_src") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5,10")>  _
        Public Property PagePrintCyber() As String
            Get
                Return CType(Me("PagePrintCyber"),String)
            End Get
            Set
                Me("PagePrintCyber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20,60")>  _
        Public Property Write_Cyber() As String
            Get
                Return CType(Me("Write_Cyber"),String)
            End Get
            Set
                Me("Write_Cyber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property DVD_Sold_BuyPrice() As String
            Get
                Return CType(Me("DVD_Sold_BuyPrice"),String)
            End Get
            Set
                Me("DVD_Sold_BuyPrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property DVD_SOLD_SOLDPRice() As String
            Get
                Return CType(Me("DVD_SOLD_SOLDPRice"),String)
            End Get
            Set
                Me("DVD_SOLD_SOLDPRice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property Benefit_DVDSold() As String
            Get
                Return CType(Me("Benefit_DVDSold"),String)
            End Get
            Set
                Me("Benefit_DVDSold") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property Cyber_MonthlyFees() As String
            Get
                Return CType(Me("Cyber_MonthlyFees"),String)
            End Get
            Set
                Me("Cyber_MonthlyFees") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1500")>  _
        Public Property Cyber_AdvanceFees() As String
            Get
                Return CType(Me("Cyber_AdvanceFees"),String)
            End Get
            Set
                Me("Cyber_AdvanceFees") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200")>  _
        Public Property CyberNormalMember_advance() As String
            Get
                Return CType(Me("CyberNormalMember_advance"),String)
            End Get
            Set
                Me("CyberNormalMember_advance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoCyberMemberID() As Boolean
            Get
                Return CType(Me("AutoCyberMemberID"),Boolean)
            End Get
            Set
                Me("AutoCyberMemberID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AukOrganization")>  _
        Public Property SoftNamex() As String
            Get
                Return CType(Me("SoftNamex"),String)
            End Get
            Set
                Me("SoftNamex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property Scaning() As String
            Get
                Return CType(Me("Scaning"),String)
            End Get
            Set
                Me("Scaning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MinDVDFIne() As String
            Get
                Return CType(Me("MinDVDFIne"),String)
            End Get
            Set
                Me("MinDVDFIne") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CafeMonthCharge() As String
            Get
                Return CType(Me("CafeMonthCharge"),String)
            End Get
            Set
                Me("CafeMonthCharge") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property CafeAdvanceFees() As String
            Get
                Return CType(Me("CafeAdvanceFees"),String)
            End Get
            Set
                Me("CafeAdvanceFees") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property INSTALL_CATEGORY() As String
            Get
                Return CType(Me("INSTALL_CATEGORY"),String)
            End Get
            Set
                Me("INSTALL_CATEGORY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CyberCafe_Member_FeesLoad() As Boolean
            Get
                Return CType(Me("CyberCafe_Member_FeesLoad"),Boolean)
            End Get
            Set
                Me("CyberCafe_Member_FeesLoad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Auk")>  _
        Public Property SettingsAccessUserID() As String
            Get
                Return CType(Me("SettingsAccessUserID"),String)
            End Get
            Set
                Me("SettingsAccessUserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("auk")>  _
        Public Property SettingsAccessUserPassword() As String
            Get
                Return CType(Me("SettingsAccessUserPassword"),String)
            End Get
            Set
                Me("SettingsAccessUserPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CyberCafeMemberLastIDNumber() As String
            Get
                Return CType(Me("CyberCafeMemberLastIDNumber"),String)
            End Get
            Set
                Me("CyberCafeMemberLastIDNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Cyber_BroadBandLastMemberID() As String
            Get
                Return CType(Me("Cyber_BroadBandLastMemberID"),String)
            End Get
            Set
                Me("Cyber_BroadBandLastMemberID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_ITEMCOST() As Boolean
            Get
                Return CType(Me("DVDOPT_ITEMCOST"),Boolean)
            End Get
            Set
                Me("DVDOPT_ITEMCOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_MTYPE() As Boolean
            Get
                Return CType(Me("DVDOPT_MTYPE"),Boolean)
            End Get
            Set
                Me("DVDOPT_MTYPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_MVERSION() As Boolean
            Get
                Return CType(Me("DVDOPT_MVERSION"),Boolean)
            End Get
            Set
                Me("DVDOPT_MVERSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_PURCHASEDATE() As Boolean
            Get
                Return CType(Me("DVDOPT_PURCHASEDATE"),Boolean)
            End Get
            Set
                Me("DVDOPT_PURCHASEDATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_COSTOMERID() As Boolean
            Get
                Return CType(Me("DVDOPT_COSTOMERID"),Boolean)
            End Get
            Set
                Me("DVDOPT_COSTOMERID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_TOTAL_BENEFIT() As Boolean
            Get
                Return CType(Me("DVDOPT_TOTAL_BENEFIT"),Boolean)
            End Get
            Set
                Me("DVDOPT_TOTAL_BENEFIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_SELFCOLUMN() As Boolean
            Get
                Return CType(Me("DVDOPT_SELFCOLUMN"),Boolean)
            End Get
            Set
                Me("DVDOPT_SELFCOLUMN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_DVDSOLDOPT() As Boolean
            Get
                Return CType(Me("DVDOPT_DVDSOLDOPT"),Boolean)
            End Get
            Set
                Me("DVDOPT_DVDSOLDOPT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_MADVANCE_TYPE() As Boolean
            Get
                Return CType(Me("DVDOPT_MADVANCE_TYPE"),Boolean)
            End Get
            Set
                Me("DVDOPT_MADVANCE_TYPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MOVIE_RENTALCOST() As Boolean
            Get
                Return CType(Me("MOVIE_RENTALCOST"),Boolean)
            End Get
            Set
                Me("MOVIE_RENTALCOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_PREVIOUS_MOVIE_COSTOMER() As Boolean
            Get
                Return CType(Me("DVDOPT_PREVIOUS_MOVIE_COSTOMER"),Boolean)
            End Get
            Set
                Me("DVDOPT_PREVIOUS_MOVIE_COSTOMER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("320")>  _
        Public Property DVDOPT_LISTBOX_WIDTHVALUE() As Integer
            Get
                Return CType(Me("DVDOPT_LISTBOX_WIDTHVALUE"),Integer)
            End Get
            Set
                Me("DVDOPT_LISTBOX_WIDTHVALUE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_DVDRENTVIEW_DURATION() As Boolean
            Get
                Return CType(Me("DVDOPT_DVDRENTVIEW_DURATION"),Boolean)
            End Get
            Set
                Me("DVDOPT_DVDRENTVIEW_DURATION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_DVDRENTVIEW_DVDRENTCOST() As Boolean
            Get
                Return CType(Me("DVDOPT_DVDRENTVIEW_DVDRENTCOST"),Boolean)
            End Get
            Set
                Me("DVDOPT_DVDRENTVIEW_DVDRENTCOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_PRODUCT_RENTCOST() As Boolean
            Get
                Return CType(Me("DVDOPT_PRODUCT_RENTCOST"),Boolean)
            End Get
            Set
                Me("DVDOPT_PRODUCT_RENTCOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_PRODUCT_SOLDVIEW() As Boolean
            Get
                Return CType(Me("DVDOPT_PRODUCT_SOLDVIEW"),Boolean)
            End Get
            Set
                Me("DVDOPT_PRODUCT_SOLDVIEW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_PRODUCT_MADTYPE() As Boolean
            Get
                Return CType(Me("DVDOPT_PRODUCT_MADTYPE"),Boolean)
            End Get
            Set
                Me("DVDOPT_PRODUCT_MADTYPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_PRODUCT_PURCHASE() As Boolean
            Get
                Return CType(Me("DVDOPT_PRODUCT_PURCHASE"),Boolean)
            End Get
            Set
                Me("DVDOPT_PRODUCT_PURCHASE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DVDOPT_USEPASSWORD() As Boolean
            Get
                Return CType(Me("DVDOPT_USEPASSWORD"),Boolean)
            End Get
            Set
                Me("DVDOPT_USEPASSWORD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property DVDOPT_SEE_LISTVIEW() As String
            Get
                Return CType(Me("DVDOPT_SEE_LISTVIEW"),String)
            End Get
            Set
                Me("DVDOPT_SEE_LISTVIEW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Cyber_ChkPassword() As Boolean
            Get
                Return CType(Me("Cyber_ChkPassword"),Boolean)
            End Get
            Set
                Me("Cyber_ChkPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ImageFiltersIndex() As Integer
            Get
                Return CType(Me("ImageFiltersIndex"),Integer)
            End Get
            Set
                Me("ImageFiltersIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_AUTOMACI_DVDID() As Boolean
            Get
                Return CType(Me("DVDOPT_AUTOMACI_DVDID"),Boolean)
            End Get
            Set
                Me("DVDOPT_AUTOMACI_DVDID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_MOVIE_ADVANCE_EQ_MTYPE() As Boolean
            Get
                Return CType(Me("DVDOPT_MOVIE_ADVANCE_EQ_MTYPE"),Boolean)
            End Get
            Set
                Me("DVDOPT_MOVIE_ADVANCE_EQ_MTYPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ALWAYS_DVDINFO_STORE() As Boolean
            Get
                Return CType(Me("ALWAYS_DVDINFO_STORE"),Boolean)
            End Get
            Set
                Me("ALWAYS_DVDINFO_STORE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_COMMENTS() As Boolean
            Get
                Return CType(Me("DVDOPT_COMMENTS"),Boolean)
            End Get
            Set
                Me("DVDOPT_COMMENTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-")>  _
        Public Property DVDID_TOKEN() As String
            Get
                Return CType(Me("DVDID_TOKEN"),String)
            End Get
            Set
                Me("DVDID_TOKEN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DVDOPT_ORDERBY() As String
            Get
                Return CType(Me("DVDOPT_ORDERBY"),String)
            End Get
            Set
                Me("DVDOPT_ORDERBY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDRNT_ALTERNATIVE() As Boolean
            Get
                Return CType(Me("DVDRNT_ALTERNATIVE"),Boolean)
            End Get
            Set
                Me("DVDRNT_ALTERNATIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDRNT_DVDCOMMENTS() As Boolean
            Get
                Return CType(Me("DVDRNT_DVDCOMMENTS"),Boolean)
            End Get
            Set
                Me("DVDRNT_DVDCOMMENTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDRNT_COS_COMMENTS() As Boolean
            Get
                Return CType(Me("DVDRNT_COS_COMMENTS"),Boolean)
            End Get
            Set
                Me("DVDRNT_COS_COMMENTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CYBER_LAST_MEMBER_LOAD() As Boolean
            Get
                Return CType(Me("CYBER_LAST_MEMBER_LOAD"),Boolean)
            End Get
            Set
                Me("CYBER_LAST_MEMBER_LOAD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DVDRENT_LAST_MEMBER() As Boolean
            Get
                Return CType(Me("DVDRENT_LAST_MEMBER"),Boolean)
            End Get
            Set
                Me("DVDRENT_LAST_MEMBER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LoadingStyle() As String
            Get
                Return CType(Me("LoadingStyle"),String)
            End Get
            Set
                Me("LoadingStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVD_RENT_V_MNAME() As Boolean
            Get
                Return CType(Me("DVD_RENT_V_MNAME"),Boolean)
            End Get
            Set
                Me("DVD_RENT_V_MNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVD_OPT_ALWAYSrEMIND() As Boolean
            Get
                Return CType(Me("DVD_OPT_ALWAYSrEMIND"),Boolean)
            End Get
            Set
                Me("DVD_OPT_ALWAYSrEMIND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOPT_BENEFIT_SHOW() As Boolean
            Get
                Return CType(Me("DVDOPT_BENEFIT_SHOW"),Boolean)
            End Get
            Set
                Me("DVDOPT_BENEFIT_SHOW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NEW_CYBER_MSG() As Boolean
            Get
                Return CType(Me("NEW_CYBER_MSG"),Boolean)
            End Get
            Set
                Me("NEW_CYBER_MSG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DIRECT_SAVE() As Boolean
            Get
                Return CType(Me("DIRECT_SAVE"),Boolean)
            End Get
            Set
                Me("DIRECT_SAVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FAST_LOAD_DVD_RENTC() As Boolean
            Get
                Return CType(Me("FAST_LOAD_DVD_RENTC"),Boolean)
            End Get
            Set
                Me("FAST_LOAD_DVD_RENTC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property NetUsingCost_Cafe_Member() As String
            Get
                Return CType(Me("NetUsingCost_Cafe_Member"),String)
            End Get
            Set
                Me("NetUsingCost_Cafe_Member") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property EXTRA_MONEY_AM() As String
            Get
                Return CType(Me("EXTRA_MONEY_AM"),String)
            End Get
            Set
                Me("EXTRA_MONEY_AM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property EXTRA_LESS() As String
            Get
                Return CType(Me("EXTRA_LESS"),String)
            End Get
            Set
                Me("EXTRA_LESS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EXTRA_COLUMN() As Boolean
            Get
                Return CType(Me("EXTRA_COLUMN"),Boolean)
            End Get
            Set
                Me("EXTRA_COLUMN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CLIENTS_ID() As Boolean
            Get
                Return CType(Me("CLIENTS_ID"),Boolean)
            End Get
            Set
                Me("CLIENTS_ID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property benefit_percent_MSol() As String
            Get
                Return CType(Me("benefit_percent_MSol"),String)
            End Get
            Set
                Me("benefit_percent_MSol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AUTOMAIC_PRODUT_NAME() As Boolean
            Get
                Return CType(Me("AUTOMAIC_PRODUT_NAME"),Boolean)
            End Get
            Set
                Me("AUTOMAIC_PRODUT_NAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PREVIOS_RECORD_PMOB() As Boolean
            Get
                Return CType(Me("PREVIOS_RECORD_PMOB"),Boolean)
            End Get
            Set
                Me("PREVIOS_RECORD_PMOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DIS_LIST_PS_SOLD() As Integer
            Get
                Return CType(Me("DIS_LIST_PS_SOLD"),Integer)
            End Get
            Set
                Me("DIS_LIST_PS_SOLD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("B")>  _
        Public Property BROAD_BAND_ID_CATE() As String
            Get
                Return CType(Me("BROAD_BAND_ID_CATE"),String)
            End Get
            Set
                Me("BROAD_BAND_ID_CATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C")>  _
        Public Property CYBERMEMBER_ID_CATE() As String
            Get
                Return CType(Me("CYBERMEMBER_ID_CATE"),String)
            End Get
            Set
                Me("CYBERMEMBER_ID_CATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
        Public Property INS_PS_CHARGE() As String
            Get
                Return CType(Me("INS_PS_CHARGE"),String)
            End Get
            Set
                Me("INS_PS_CHARGE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property VAT_PER_PS() As String
            Get
                Return CType(Me("VAT_PER_PS"),String)
            End Get
            Set
                Me("VAT_PER_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AFTER_SOLD_PRINT_PS() As Boolean
            Get
                Return CType(Me("AFTER_SOLD_PRINT_PS"),Boolean)
            End Get
            Set
                Me("AFTER_SOLD_PRINT_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DEL_SOLD_PS() As Boolean
            Get
                Return CType(Me("DEL_SOLD_PS"),Boolean)
            End Get
            Set
                Me("DEL_SOLD_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BENEFIT_SHOW_PS() As Boolean
            Get
                Return CType(Me("BENEFIT_SHOW_PS"),Boolean)
            End Get
            Set
                Me("BENEFIT_SHOW_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PURCHASE_SHOW_PS() As Boolean
            Get
                Return CType(Me("PURCHASE_SHOW_PS"),Boolean)
            End Get
            Set
                Me("PURCHASE_SHOW_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CHECK_BENEFIT_PS() As Boolean
            Get
                Return CType(Me("CHECK_BENEFIT_PS"),Boolean)
            End Get
            Set
                Me("CHECK_BENEFIT_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property BEFORE_SOLD_MSG_PS() As Boolean
            Get
                Return CType(Me("BEFORE_SOLD_MSG_PS"),Boolean)
            End Get
            Set
                Me("BEFORE_SOLD_MSG_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WARN_M_READONLY_PS() As Boolean
            Get
                Return CType(Me("WARN_M_READONLY_PS"),Boolean)
            End Get
            Set
                Me("WARN_M_READONLY_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PURCHASE_RO_PS() As Boolean
            Get
                Return CType(Me("PURCHASE_RO_PS"),Boolean)
            End Get
            Set
                Me("PURCHASE_RO_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property BENEFIT_RO_PS() As Boolean
            Get
                Return CType(Me("BENEFIT_RO_PS"),Boolean)
            End Get
            Set
                Me("BENEFIT_RO_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INVOICE")>  _
        Public Property TITLE_INVOICE_PS() As String
            Get
                Return CType(Me("TITLE_INVOICE_PS"),String)
            End Get
            Set
                Me("TITLE_INVOICE_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property COMMENTS_RP_PS() As String
            Get
                Return CType(Me("COMMENTS_RP_PS"),String)
            End Get
            Set
                Me("COMMENTS_RP_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property COM_ADDRESS() As String
            Get
                Return CType(Me("COM_ADDRESS"),String)
            End Get
            Set
                Me("COM_ADDRESS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SHOW_COMPANYN_PS_R() As Boolean
            Get
                Return CType(Me("SHOW_COMPANYN_PS_R"),Boolean)
            End Get
            Set
                Me("SHOW_COMPANYN_PS_R") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DVDMEBER_ID_SR() As String
            Get
                Return CType(Me("DVDMEBER_ID_SR"),String)
            End Get
            Set
                Me("DVDMEBER_ID_SR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DVDMEMBER_STATW() As String
            Get
                Return CType(Me("DVDMEMBER_STATW"),String)
            End Get
            Set
                Me("DVDMEMBER_STATW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AUTOMATICID_DVDMEBER() As Boolean
            Get
                Return CType(Me("AUTOMATICID_DVDMEBER"),Boolean)
            End Get
            Set
                Me("AUTOMATICID_DVDMEBER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\")>  _
        Public Property BACKUP_FOLDER() As String
            Get
                Return CType(Me("BACKUP_FOLDER"),String)
            End Get
            Set
                Me("BACKUP_FOLDER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property MINIMAM_DBSIZE() As Decimal
            Get
                Return CType(Me("MINIMAM_DBSIZE"),Decimal)
            End Get
            Set
                Me("MINIMAM_DBSIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property REPLACE_DB() As Boolean
            Get
                Return CType(Me("REPLACE_DB"),Boolean)
            End Get
            Set
                Me("REPLACE_DB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property DAYS_BACKYP() As Decimal
            Get
                Return CType(Me("DAYS_BACKYP"),Decimal)
            End Get
            Set
                Me("DAYS_BACKYP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VIEW_DETAILS_PS() As Boolean
            Get
                Return CType(Me("VIEW_DETAILS_PS"),Boolean)
            End Get
            Set
                Me("VIEW_DETAILS_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property RENT_MOVIE_BY_DVDOPT() As Integer
            Get
                Return CType(Me("RENT_MOVIE_BY_DVDOPT"),Integer)
            End Get
            Set
                Me("RENT_MOVIE_BY_DVDOPT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property REPORT_AS_MEMO_MSOLD() As Boolean
            Get
                Return CType(Me("REPORT_AS_MEMO_MSOLD"),Boolean)
            End Get
            Set
                Me("REPORT_AS_MEMO_MSOLD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SHOW_MSG_BEFORE_MS() As Boolean
            Get
                Return CType(Me("SHOW_MSG_BEFORE_MS"),Boolean)
            End Get
            Set
                Me("SHOW_MSG_BEFORE_MS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SAVE_CLIENT_MSOLD() As Boolean
            Get
                Return CType(Me("SAVE_CLIENT_MSOLD"),Boolean)
            End Get
            Set
                Me("SAVE_CLIENT_MSOLD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CLIENT_NAME_SHOW_PS() As Boolean
            Get
                Return CType(Me("CLIENT_NAME_SHOW_PS"),Boolean)
            End Get
            Set
                Me("CLIENT_NAME_SHOW_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SHOW_MOVIE_VER_MSOLD() As Boolean
            Get
                Return CType(Me("SHOW_MOVIE_VER_MSOLD"),Boolean)
            End Get
            Set
                Me("SHOW_MOVIE_VER_MSOLD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BackUp_LAstDate() As Date
            Get
                Return CType(Me("BackUp_LAstDate"),Date)
            End Get
            Set
                Me("BackUp_LAstDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DRENT_ADEW_LASTMOVIE() As Boolean
            Get
                Return CType(Me("DRENT_ADEW_LASTMOVIE"),Boolean)
            End Get
            Set
                Me("DRENT_ADEW_LASTMOVIE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PS_LASTL_ADDINGNEW() As Boolean
            Get
                Return CType(Me("PS_LASTL_ADDINGNEW"),Boolean)
            End Get
            Set
                Me("PS_LASTL_ADDINGNEW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CyberLastDate() As Date
            Get
                Return CType(Me("CyberLastDate"),Date)
            End Get
            Set
                Me("CyberLastDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MobileLastDate() As Date
            Get
                Return CType(Me("MobileLastDate"),Date)
            End Get
            Set
                Me("MobileLastDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WARM_SHOW_PS() As Boolean
            Get
                Return CType(Me("WARM_SHOW_PS"),Boolean)
            End Get
            Set
                Me("WARM_SHOW_PS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VIRTUAL_CYBERCAFE() As Boolean
            Get
                Return CType(Me("VIRTUAL_CYBERCAFE"),Boolean)
            End Get
            Set
                Me("VIRTUAL_CYBERCAFE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VIRTUAL_MOVIES_COLLECTION() As Boolean
            Get
                Return CType(Me("VIRTUAL_MOVIES_COLLECTION"),Boolean)
            End Get
            Set
                Me("VIRTUAL_MOVIES_COLLECTION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property CyberMainFormTrans() As Integer
            Get
                Return CType(Me("CyberMainFormTrans"),Integer)
            End Get
            Set
                Me("CyberMainFormTrans") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BUSDATE_MOB() As Boolean
            Get
                Return CType(Me("BUSDATE_MOB"),Boolean)
            End Get
            Set
                Me("BUSDATE_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MOBCOM_NAME_MOB() As Boolean
            Get
                Return CType(Me("MOBCOM_NAME_MOB"),Boolean)
            End Get
            Set
                Me("MOBCOM_NAME_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TRANS_MOB() As Boolean
            Get
                Return CType(Me("TRANS_MOB"),Boolean)
            End Get
            Set
                Me("TRANS_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ENTER_TOnEXT_MOB() As Boolean
            Get
                Return CType(Me("ENTER_TOnEXT_MOB"),Boolean)
            End Get
            Set
                Me("ENTER_TOnEXT_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISCOUNT_MOB() As Boolean
            Get
                Return CType(Me("DISCOUNT_MOB"),Boolean)
            End Get
            Set
                Me("DISCOUNT_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property BENEFIT_MOB() As Boolean
            Get
                Return CType(Me("BENEFIT_MOB"),Boolean)
            End Get
            Set
                Me("BENEFIT_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property S_MSG_TIME_MOB() As Boolean
            Get
                Return CType(Me("S_MSG_TIME_MOB"),Boolean)
            End Get
            Set
                Me("S_MSG_TIME_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CURRENT_BALANCE_MOB() As Boolean
            Get
                Return CType(Me("CURRENT_BALANCE_MOB"),Boolean)
            End Get
            Set
                Me("CURRENT_BALANCE_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TELECOM_N_C_B_MOB() As Boolean
            Get
                Return CType(Me("TELECOM_N_C_B_MOB"),Boolean)
            End Get
            Set
                Me("TELECOM_N_C_B_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property REF_DUE_BENEFIT_MOB() As Boolean
            Get
                Return CType(Me("REF_DUE_BENEFIT_MOB"),Boolean)
            End Get
            Set
                Me("REF_DUE_BENEFIT_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NEXT_B_D_L_MOB() As Boolean
            Get
                Return CType(Me("NEXT_B_D_L_MOB"),Boolean)
            End Get
            Set
                Me("NEXT_B_D_L_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property mAKE_TRANS_bAL() As Boolean
            Get
                Return CType(Me("mAKE_TRANS_bAL"),Boolean)
            End Get
            Set
                Me("mAKE_TRANS_bAL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ROW_SEL_MOB() As String
            Get
                Return CType(Me("ROW_SEL_MOB"),String)
            End Get
            Set
                Me("ROW_SEL_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CUR_INFO_SHOW() As String
            Get
                Return CType(Me("CUR_INFO_SHOW"),String)
            End Get
            Set
                Me("CUR_INFO_SHOW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Calibri, 15.75pt")>  _
        Public Property FONT_INFO_MOB() As String
            Get
                Return CType(Me("FONT_INFO_MOB"),String)
            End Get
            Set
                Me("FONT_INFO_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property INFOR_HEIGHT_MOB() As Integer
            Get
                Return CType(Me("INFOR_HEIGHT_MOB"),Integer)
            End Get
            Set
                Me("INFOR_HEIGHT_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TOOK_WHOL_INFO_MOB() As Boolean
            Get
                Return CType(Me("TOOK_WHOL_INFO_MOB"),Boolean)
            End Get
            Set
                Me("TOOK_WHOL_INFO_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EXTRA_M_TR() As Boolean
            Get
                Return CType(Me("EXTRA_M_TR"),Boolean)
            End Get
            Set
                Me("EXTRA_M_TR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EXTRA_EFF2_MOB() As String
            Get
                Return CType(Me("EXTRA_EFF2_MOB"),String)
            End Get
            Set
                Me("EXTRA_EFF2_MOB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("18")>  _
        Public Property NewMovies_MaxRentH() As String
            Get
                Return CType(Me("NewMovies_MaxRentH"),String)
            End Get
            Set
                Me("NewMovies_MaxRentH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property InsMNewDays_DvdOpt() As String
            Get
                Return CType(Me("InsMNewDays_DvdOpt"),String)
            End Get
            Set
                Me("InsMNewDays_DvdOpt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowDue_Mob() As Boolean
            Get
                Return CType(Me("ShowDue_Mob"),Boolean)
            End Get
            Set
                Me("ShowDue_Mob") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property DVOpt_DelRowsKeep() As String
            Get
                Return CType(Me("DVOpt_DelRowsKeep"),String)
            End Get
            Set
                Me("DVOpt_DelRowsKeep") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DVDOpt_PasswordDelRows() As Boolean
            Get
                Return CType(Me("DVDOpt_PasswordDelRows"),Boolean)
            End Get
            Set
                Me("DVDOpt_PasswordDelRows") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LOGINPASS() As Boolean
            Get
                Return CType(Me("LOGINPASS"),Boolean)
            End Get
            Set
                Me("LOGINPASS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Dont_DeleteDVDRentDeleted() As Boolean
            Get
                Return CType(Me("Dont_DeleteDVDRentDeleted"),Boolean)
            End Get
            Set
                Me("Dont_DeleteDVDRentDeleted") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NetReg() As Boolean
            Get
                Return CType(Me("NetReg"),Boolean)
            End Get
            Set
                Me("NetReg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ping [IP]")>  _
        Public Property PingCommand() As String
            Get
                Return CType(Me("PingCommand"),String)
            End Get
            Set
                Me("PingCommand") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NetRegBlock() As Boolean
            Get
                Return CType(Me("NetRegBlock"),Boolean)
            End Get
            Set
                Me("NetRegBlock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CyberRoundFigure() As Boolean
            Get
                Return CType(Me("CyberRoundFigure"),Boolean)
            End Get
            Set
                Me("CyberRoundFigure") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property CyberRoundFigureValue() As String
            Get
                Return CType(Me("CyberRoundFigureValue"),String)
            End Get
            Set
                Me("CyberRoundFigureValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DynamicCostReplace() As Boolean
            Get
                Return CType(Me("DynamicCostReplace"),Boolean)
            End Get
            Set
                Me("DynamicCostReplace") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CyberPack_Pro.My.MySettings
            Get
                Return Global.CyberPack_Pro.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
